---
graphql:
  replicaCount: 2
  image:
    repository: ghcr.io/jvaldron/flyball-planner/graphql
    tag: ""
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 4000
  env:
    NODE_ENV: production
    DB_USER: flyball_user
    DB_NAME: flyball_practice
    DB_HOST: postgresql
    DB_PORT: 5432
    DB_SSLMODE: disable
    ALLOWED_ORIGINS: "http://flyball.local"
  secret:
    enabled: true
    existingSecret: ""

frontend:
  replicaCount: 1
  image:
    repository: ghcr.io/jvaldron/flyball-planner/frontend
    tag: ""
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  env:
    GRAPHQL_BASE_URL: /graphql

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  host: flyball.local

httpRoute:
  enabled: false
  gateway:
    name: "nginx"
    namespace: "kube-system"
  host: "flyball.local"

postgresql:
  enabled: true
  image:
    repository: postgres
    tag: "16-alpine"
    pullPolicy: IfNotPresent
  auth:
    username: flyball_user
    database: flyball_practice
  persistence:
    enabled: true
    size: 1Gi
    storageClass: ""
  resources: {}
  service:
    type: ClusterIP
    port: 5432
