---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flyball.fullname" . }}-db-secret
  labels:
    {{- include "flyball.api.labels" . | nindent 4 }}
stringData:
  password: {{ .Values.postgresql.auth.password }}
