---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flyball.fullname" . }}-api
  labels:
    {{- include "flyball.api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 8080
  selector:
    {{- include "flyball.api.labels" . | nindent 4 }}
