---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flyball.fullname" . }}-frontend
  labels:
    {{- include "flyball.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
  selector:
    {{- include "flyball.frontend.labels" . | nindent 4 }}
