---
{{- if .Values.api.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flyball.fullname" . }}-db-secret
  labels:
    {{- include "flyball.api.labels" . | nindent 4 }}
stringData:
  # TODO: Password will change on subsequent deployments
  postgres-password: {{ .Values.postgresql.auth.password | default (randAlphaNum 16) }}
  password: {{ .Values.api.secret.password | default (randAlphaNum 16) }}
{{- end }}
