---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flyball.fullname" . }}-graphql
  labels:
    {{- include "flyball.graphql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.graphql.service.type }}
  ports:
    - port: {{ .Values.graphql.service.port }}
      targetPort: 8080
  selector:
    {{- include "flyball.graphql.labels" . | nindent 4 }}
