---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flyball-planner.fullname" . }}-frontend
  labels:
    {{- include "flyball-planner.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "flyball-planner.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "flyball-planner.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          env:
            - name: GRAPHQL_BASE_URL
              value: {{ .Values.frontend.env.GRAPHQL_BASE_URL | default "/graphql" }}
            - name: WS_BASE_URL
              value: {{ .Values.frontend.env.WS_BASE_URL | default "/subscriptions" }}
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 1
            periodSeconds: 3
