---
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "flyball.fullname" . }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        host: {{ .Values.ingress.host }}
        paths:
          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: {{ include "flyball.fullname" . }}-graphql
                port:
                  number: 4000
          - path: /subscriptions
            pathType: Prefix
            backend:
              service:
                name: {{ include "flyball.fullname" . }}-graphql
                port:
                  number: 4000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "flyball.fullname" . }}-frontend
                port:
                  number: 80
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
{{- end }}
