{{- if and .Values.graphql.jwtSecret.enabled (not .Values.graphql.jwtSecret.existingSecret) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flyball-planner.fullname" . }}-jwt-secret-generator
  labels:
    {{- include "flyball-planner.labels" . | nindent 4 }}
    app.kubernetes.io/component: jwt-secret-generator
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-delete
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "flyball-planner.fullname" . }}-jwt-secret-generator
  labels:
    {{- include "flyball-planner.labels" . | nindent 4 }}
    app.kubernetes.io/component: jwt-secret-generator
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-delete
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "flyball-planner.fullname" . }}-jwt-secret-generator
  labels:
    {{- include "flyball-planner.labels" . | nindent 4 }}
    app.kubernetes.io/component: jwt-secret-generator
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-delete
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "flyball-planner.fullname" . }}-jwt-secret-generator
subjects:
- kind: ServiceAccount
  name: {{ include "flyball-planner.fullname" . }}-jwt-secret-generator
  namespace: {{ .Release.Namespace }}
{{- end }}
