apiVersion: v1
entries:
  flyball-planner:
  - apiVersion: v2
    appVersion: v1.0.0
    created: "2025-09-13T22:59:02.966413098Z"
    description: Flyball Planner - A web application for managing flyball practices
    digest: d8e75ec55773e1af448da346aa017d2936b9c2aa78f583577f4724f49ad76228
    home: https://github.com/jvaldron/flyball-planner
    maintainers:
    - email: jason@valdron.ca
      name: Jason Valdron
    name: flyball-planner
    sources:
    - https://github.com/jvaldron/flyball-planner
    type: application
    urls:
    - https://jValdron.github.io/flyball-planner/charts/flyball-planner-1.0.0.tgz
    version: 1.0.0
generated: "2025-09-13T22:59:02.965839452Z"
