apiVersion: v1
entries:
  flyball-planner:
  - apiVersion: v2
    appVersion: v1.0.0
    created: "2025-09-14T01:48:30.459866281Z"
    description: Flyball Planner - A web application for managing flyball practices
    digest: ac7c15929e4c2cfc92e1ae320d6bd2cca0d3f0042cd4c8aa4be46cd67664aadf
    home: https://github.com/jvaldron/flyball-planner
    maintainers:
    - email: jason@valdron.ca
      name: Jason Valdron
    name: flyball-planner
    sources:
    - https://github.com/jvaldron/flyball-planner
    type: application
    urls:
    - https://jValdron.github.io/flyball-planner/charts/flyball-planner-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: v1.0.0
    created: "2025-09-14T01:48:30.459479184Z"
    description: Flyball Planner - A web application for managing flyball practices
    digest: d8e75ec55773e1af448da346aa017d2936b9c2aa78f583577f4724f49ad76228
    home: https://github.com/jvaldron/flyball-planner
    maintainers:
    - email: jason@valdron.ca
      name: Jason Valdron
    name: flyball-planner
    sources:
    - https://github.com/jvaldron/flyball-planner
    type: application
    urls:
    - https://jValdron.github.io/flyball-planner/charts/flyball-planner-1.0.0.tgz
    version: 1.0.0
generated: "2025-09-14T01:48:30.458935266Z"
