---
api:
  replicaCount: 2
  image:
    repository: ghcr.io/jvaldron/flyball-practice-planner/api
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  env:
    DB_USER: flyball_user
    DB_NAME: flyball_practice
    DB_HOST: flyball-planner-postgresql
    DB_PORT: 5432
    DB_SSLMODE: disable
  secret:
    enabled: true

frontend:
  replicaCount: 1
  image:
    repository: ghcr.io/jvaldron/flyball-practice-planner/frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  env:
    API_BASE_URL: /api

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  host: flyball.local

httpRoute:
  enabled: false
  gateway:
    name: "nginx"
    namespace: "kube-system"
  host: "flyball.local"

postgresql:
  enabled: true
  auth:
    username: flyball_user
    database: flyball_practice
    # TODO: Update existingSecret to pull in release name automatically.
    existingSecret: flyball-planner-flyball-practice-planner-db-secret
