---
api:
  replicaCount: 1
  image:
    repository: my-registry/flyball-api
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  env:
    DB_USER: flyball_user
    DB_NAME: flyball_practice
    DB_HOST: postgresql
    DB_PORT: 5432
    DB_SSLMODE: disable
  secret:
    enabled: true
    DB_PASSWORD: "{{ .Values.postgresql.auth.password }}"

frontend:
  replicaCount: 1
  image:
    repository: my-registry/flyball-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  env:
    API_BASE_URL: /api

postgresql:
  enabled: true
  auth:
    username: flyball_user
    database: flyball_practice
    existingSecret: flyball-db-secret
